name: ci
on:
  pull_request:
  push:
    branches:
      - master
      - llvm16
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  aarch64-macos-debug:
    runs-on: [self-hosted, macOS, aarch64]
    env:
      ARCH: "aarch64"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: ci/aarch64-macos-debug.sh
